backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets

local_backend: true

collections:
  - name: units
    label: Units
    folder: content/units
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: courses, label: Courses }
      - { name: body, label: Body, widget: markdown }
  - name: courses
    label: Courses
    folder: content/courses
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: code, label: Code }
      - { name: body, label: Body, widget: markdown }
